[project]
name = "saving_planner_server"
description = "It demonstrate you how much you will grow your saving with utilising several account."
readme = "README.md"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3.12.2",
]
requires-python = "==3.12.*"
dependencies = [
    "numpy~=1.21",
    "streamlit"
]
dynamic = ["version"]

[project.optional-dependencies]
dev = [
    "mypy",
    "pre-commit",
]